// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TallerPro.Infrastructure.Persistence;

#nullable disable

#pragma warning disable IDE0161 // EF scaffolded file uses block-scoped namespace

namespace TallerPro.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TallerProDbContext))]
    partial class TallerProDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("core")
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TallerPro.Domain.Auth.PlatformAdmin", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<long?>("CreatedByPlatformId")
                        .HasColumnType("bigint");

                    b.Property<long?>("CreatedByUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(254)")
                        .UseCollation("Latin1_General_100_CI_AI_SC_UTF8");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<long?>("UpdatedByPlatformId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByPlatformId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UQ_PlatformAdmins_Email")
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("UpdatedByPlatformId");

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("PlatformAdmins", "auth", t =>
                        {
                            t.HasCheckConstraint("CK_PlatformAdmins_CreatedByExclusive", "[CreatedByUserId] IS NULL OR [CreatedByPlatformId] IS NULL");

                            t.HasCheckConstraint("CK_PlatformAdmins_EmailLowercase", "[Email] = LOWER([Email])");

                            t.HasCheckConstraint("CK_PlatformAdmins_UpdatedByExclusive", "[UpdatedByUserId] IS NULL OR [UpdatedByPlatformId] IS NULL");
                        });
                });

            modelBuilder.Entity("TallerPro.Domain.Auth.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<long?>("CreatedByPlatformId")
                        .HasColumnType("bigint");

                    b.Property<long?>("CreatedByUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(254)")
                        .UseCollation("Latin1_General_100_CI_AI_SC_UTF8");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<long?>("UpdatedByPlatformId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByPlatformId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UQ_Users_Email")
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("UpdatedByPlatformId");

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("Users", "auth", t =>
                        {
                            t.HasCheckConstraint("CK_Users_CreatedByExclusive", "[CreatedByUserId] IS NULL OR [CreatedByPlatformId] IS NULL");

                            t.HasCheckConstraint("CK_Users_EmailLowercase", "[Email] = LOWER([Email])");

                            t.HasCheckConstraint("CK_Users_UpdatedByExclusive", "[UpdatedByUserId] IS NULL OR [UpdatedByPlatformId] IS NULL");
                        });
                });

            modelBuilder.Entity("TallerPro.Domain.Auth.UserBranchAccess", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<long?>("CreatedByPlatformId")
                        .HasColumnType("bigint");

                    b.Property<long?>("CreatedByUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<byte>("Role")
                        .HasColumnType("tinyint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<long?>("UpdatedByPlatformId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BranchId")
                        .HasDatabaseName("IX_UBA_BranchId")
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("CreatedByPlatformId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_UBA_TenantId")
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("UpdatedByPlatformId");

                    b.HasIndex("UpdatedByUserId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_UBA_UserId")
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("UserId", "BranchId")
                        .IsUnique()
                        .HasDatabaseName("UQ_UBA_User_Branch")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("UserBranchAccesses", "auth", t =>
                        {
                            t.HasCheckConstraint("CK_UBA_CreatedByExclusive", "[CreatedByUserId] IS NULL OR [CreatedByPlatformId] IS NULL");

                            t.HasCheckConstraint("CK_UBA_RoleValid", "[Role] IN (0, 1, 2)");

                            t.HasCheckConstraint("CK_UBA_UpdatedByExclusive", "[UpdatedByUserId] IS NULL OR [UpdatedByPlatformId] IS NULL");
                        });
                });

            modelBuilder.Entity("TallerPro.Domain.Tenants.Branch", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<long?>("CreatedByPlatformId")
                        .HasColumnType("bigint");

                    b.Property<long?>("CreatedByUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(120)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<long?>("UpdatedByPlatformId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByPlatformId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_Branches_TenantId")
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("UpdatedByPlatformId");

                    b.HasIndex("UpdatedByUserId");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_Branches_TenantId_Code")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("Branches", "core", t =>
                        {
                            t.HasCheckConstraint("CK_Branches_CodeFormat", "[Code] NOT LIKE '%[^A-Z0-9-]%'");

                            t.HasCheckConstraint("CK_Branches_CreatedByExclusive", "[CreatedByUserId] IS NULL OR [CreatedByPlatformId] IS NULL");

                            t.HasCheckConstraint("CK_Branches_UpdatedByExclusive", "[UpdatedByUserId] IS NULL OR [UpdatedByPlatformId] IS NULL");
                        });
                });

            modelBuilder.Entity("TallerPro.Domain.Tenants.Tenant", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<long?>("CreatedByPlatformId")
                        .HasColumnType("bigint");

                    b.Property<long?>("CreatedByUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(120)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("varchar(40)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<long?>("UpdatedByPlatformId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByPlatformId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("UQ_Tenants_Slug")
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Tenants_Status")
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("UpdatedByPlatformId");

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("Tenants", "core", t =>
                        {
                            t.HasCheckConstraint("CK_Tenants_CreatedByExclusive", "[CreatedByUserId] IS NULL OR [CreatedByPlatformId] IS NULL");

                            t.HasCheckConstraint("CK_Tenants_SlugLowercase", "[Slug] = LOWER([Slug])");

                            t.HasCheckConstraint("CK_Tenants_UpdatedByExclusive", "[UpdatedByUserId] IS NULL OR [UpdatedByPlatformId] IS NULL");
                        });
                });

            modelBuilder.Entity("TallerPro.Domain.Auth.PlatformAdmin", b =>
                {
                    b.HasOne("TallerPro.Domain.Auth.PlatformAdmin", null)
                        .WithMany()
                        .HasForeignKey("CreatedByPlatformId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TallerPro.Domain.Auth.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TallerPro.Domain.Auth.PlatformAdmin", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByPlatformId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TallerPro.Domain.Auth.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("TallerPro.Domain.Auth.User", b =>
                {
                    b.HasOne("TallerPro.Domain.Auth.PlatformAdmin", null)
                        .WithMany()
                        .HasForeignKey("CreatedByPlatformId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TallerPro.Domain.Auth.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TallerPro.Domain.Auth.PlatformAdmin", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByPlatformId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TallerPro.Domain.Auth.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("TallerPro.Domain.Auth.UserBranchAccess", b =>
                {
                    b.HasOne("TallerPro.Domain.Tenants.Branch", null)
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_UBA_Branches");

                    b.HasOne("TallerPro.Domain.Auth.PlatformAdmin", null)
                        .WithMany()
                        .HasForeignKey("CreatedByPlatformId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TallerPro.Domain.Auth.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TallerPro.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_UBA_Tenants");

                    b.HasOne("TallerPro.Domain.Auth.PlatformAdmin", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByPlatformId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TallerPro.Domain.Auth.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TallerPro.Domain.Auth.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_UBA_Users");
                });

            modelBuilder.Entity("TallerPro.Domain.Tenants.Branch", b =>
                {
                    b.HasOne("TallerPro.Domain.Auth.PlatformAdmin", null)
                        .WithMany()
                        .HasForeignKey("CreatedByPlatformId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TallerPro.Domain.Auth.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TallerPro.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Branches_Tenants");

                    b.HasOne("TallerPro.Domain.Auth.PlatformAdmin", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByPlatformId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TallerPro.Domain.Auth.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("TallerPro.Domain.Tenants.Tenant", b =>
                {
                    b.HasOne("TallerPro.Domain.Auth.PlatformAdmin", null)
                        .WithMany()
                        .HasForeignKey("CreatedByPlatformId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TallerPro.Domain.Auth.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TallerPro.Domain.Auth.PlatformAdmin", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByPlatformId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TallerPro.Domain.Auth.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}

#pragma warning restore IDE0161
